### ISSUE TITLE
NoSuchMethodError: com.google.common.collect.ImmutableList.toImmutableList()Ljava/util/stream/Collector; after upgrade to 2.0.16

### ISSUE THREAD

**Issue by koral--** [google/error-prone#528]
Not 100% sure where exactly is the bug but first reporting here. CC @tbroyer because I'm using `net.ltgt.errorprone:0.0.8`. With errorprone 2.0.15 everything worked fine.
Most important part of the stacktrace:
```
java.lang.NoSuchMethodError: com.google.common.collect.ImmutableList.toImmutableList()Ljava/util/stream/Collector;
	at com.google.errorprone.bugpatterns.ImmutableModification.<clinit>(ImmutableModification.java:127)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.google.errorprone.scanner.ScannerSupplierImpl$1.apply(ScannerSupplierImpl.java:65)
	at com.google.errorprone.scanner.ScannerSupplierImpl$1.apply(ScannerSupplierImpl.java:61)
	at com.google.common.collect.Iterators$7.transform(Iterators.java:750)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at com.google.errorprone.scanner.ErrorProneScanner.<init>(ErrorProneScanner.java:186)
	at com.google.errorprone.scanner.ScannerSupplierImpl.get(ScannerSupplierImpl.java:75)
	at com.google.errorprone.scanner.ScannerSupplierImpl.get(ScannerSupplierImpl.java:40)
	at com.google.errorprone.ErrorProneAnalyzer.lambda$scansPlugins$0(ErrorProneAnalyzer.java:75)
	at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:120)
	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:145)
	at com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:120)
	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1277)
	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1226)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:840)
	at com.sun.tools.javac.main.Main.compile(Main.java:257)
	at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:229)
	at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:107)
	at com.google.errorprone.ErrorProneCompiler.run(ErrorProneCompiler.java:128)
	at com.google.errorprone.ErrorProneCompiler.compile(ErrorProneCompiler.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.ltgt.gradle.errorprone.ErrorProneCompiler.execute(ErrorProneCompiler.java:57)
	at net.ltgt.gradle.errorprone.ErrorProneCompiler.execute(ErrorProneCompiler.java:25)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:104)
```
Sample project: https://github.com/koral--/GithubClient
Steps to reproduce: invoke `./gradlew assembleDebug`

Failing build log (incl. JDK and Gradle versions): https://jitpack.io/com/github/koral--/GithubClient/1e080266b9/build.log
Successful build log after forcing errorprone 2.0.15: https://jitpack.io/com/github/koral--/GithubClient/1e080266b9/build.log

**Comment by cushon** [comment]
`toImmutableList` was added in guava 21, which Error Prone 2.0.16 depends on.

**Comment by koral--** [comment]
Thanks. Guava version was forcibly set there to 20 to work around another (non-errorprone) issue. After changing to 21 it works fine.

**Comment by trejkaz** [comment]
I'm getting this error too. Does this mean errorprone can't be used on projects which still depend on Guava 20.0? I would have thought that a dependency of a compiler wouldn't conflict with the dependency for the code it's compiling.
