### ISSUE TITLE
Error-prone OpenJDK17 JavaLangClash breaks the plugin in Docker only

### ISSUE THREAD

**Issue by tstejl** [google/error-prone#2708]
Gradle 7.3 builds fine on local with OpenJDK 17.0.1, but failed to build in Docker with openjdk:17-alpine
```
> Task :bootBuildInfo
#10 61.12 > Task :compileJava
#10 62.02 /home/gradle/src/src/main/java/com/__DETRACTED__/ProductRoles.java:17: error: An unhandled exception was thrown by the Error Prone static analysis plugin.
#10 62.02 public class ProductRoles {
#10 62.02        ^
#10 62.02      Please report this at https://github.com/google/error-prone/issues/new and include the following:
#10 62.02   
#10 62.02      error-prone version: 2.10.0
#10 62.12      BugPattern: JavaLangClash
#10 62.12      Stack Trace:
#10 62.12      java.lang.LinkageError: com.sun.tools.javac.code.Scope.anyMatch(java.util.function.Predicate)
#10 62.12       at com.google.errorprone.util.ErrorProneScope.getMethodOrDie(ErrorProneScope.java:131)
#10 62.12       at com.google.errorprone.util.ErrorProneScope.getImpl(ErrorProneScope.java:94)
#10 62.12       at com.google.errorprone.util.ErrorProneScope.<clinit>(ErrorProneScope.java:73)
#10 62.12       at com.google.errorprone.util.ASTHelpers.scope(ASTHelpers.java:2240)
#10 62.12       at com.google.errorprone.bugpatterns.JavaLangClash.check(JavaLangClash.java:76)
#10 62.12       at com.google.errorprone.bugpatterns.JavaLangClash.matchClass(JavaLangClash.java:54)
#10 62.12       at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:449)
#10 62.12       at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:547)
#10 62.12       at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:150)
#10 62.12       at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:840)
#10 62.12       at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
#10 62.12       at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
#10 62.12       at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
#10 62.12       at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:109)
#10 62.12       at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:117)
#10 62.12       at jdk.compiler/com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:148)
#10 62.12       at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:560)
#10 62.12       at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:150)
#10 62.12       at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:611)
#10 62.12       at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:60)
#10 62.12       at com.google.errorprone.scanner.Scanner.scan(Scanner.java:58)
#10 62.12       at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
#10 62.12       at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:152)
#10 62.12       at jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:132)
#10 62.12       at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1421)
#10 62.12       at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1368)
#10 62.12       at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:960)
#10 62.12       at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
#10 62.12       at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.invocationHelper(JavacTaskImpl.java:152)
#10 62.13       at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
#10 62.13       at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
#10 62.13       at org.gradle.internal.compiler.java.IncrementalCompileTask.call(IncrementalCompileTask.java:89)
#10 62.13       at org.gradle.api.internal.tasks.compile.AnnotationProcessingCompileTask.call(AnnotationProcessingCompileTask.java:94)
#10 62.13       at org.gradle.api.internal.tasks.compile.ResourceCleaningCompilationTask.call(ResourceCleaningCompilationTask.java:57)
#10 62.13       at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:54)
#10 62.13       at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:39)
#10 62.13       at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerWorkAction.execute(AbstractDaemonCompiler.java:135)
#10 62.13       at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
#10 62.13       at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:49)
#10 62.13       at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:43)
#10 62.13       at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)
#10 62.13       at org.gradle.workers.internal.AbstractClassLoaderWorker.executeInClassLoader(AbstractClassLoaderWorker.java:43)
#10 62.13       at org.gradle.workers.internal.FlatClassLoaderWorker.run(FlatClassLoaderWorker.java:32)
#10 62.13       at org.gradle.workers.internal.FlatClassLoaderWorker.run(FlatClassLoaderWorker.java:22)
#10 62.13       at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:85)
#10 62.13       at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:55)
#10 62.13       at org.gradle.process.internal.worker.request.WorkerAction$1.call(WorkerAction.java:138)
#10 62.13       at org.gradle.process.internal.worker.child.WorkerLogEventListener.withWorkerLoggingProtocol(WorkerLogEventListener.java:41)
#10 62.13       at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:135)
#10 62.13       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#10 62.13       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
#10 62.13       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#10 62.13       at java.base/java.lang.reflect.Method.invoke(Method.java:568)
#10 62.13       at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
#10 62.13       at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
#10 62.13       at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
#10 62.13       at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
#10 62.14       at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
#10 62.14       at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
#10 62.14       at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
#10 62.14       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
#10 62.14       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
#10 62.14       at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61)
#10 62.14       at java.base/java.lang.Thread.run(Thread.java:831)
#10 62.14   Caused by: java.lang.NoSuchMethodException: com.sun.tools.javac.code.Scope.anyMatch(java.util.function.Predicate)
#10 62.14       at java.base/java.lang.Class.getMethod(Class.java:2202)
#10 62.14       at com.google.errorprone.util.ErrorProneScope.getMethodOrDie(ErrorProneScope.java:129)
#10 62.14       ... 63 more
#10 62.14 1 error
#10 62.22 
#10 62.22 > Task :compileJava FAILED
#10 62.24 * Exception is:
#10 62.24 org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':compileJava'.
#10 62.24       at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:145)
#10 62.24       at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
#10 62.24       at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:143)
#10 62.24       at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:131)
#10 62.24       at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:77)
#10 62.24       at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
#10 62.24       at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
#10 62.24       at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
#10 62.24       at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
#10 62.24       at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
#10 62.25       at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
#10 62.25       at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
#10 62.25       at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
#10 62.25       at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
#10 62.25       at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
#10 62.25       at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
#10 62.25       at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
#10 62.25       at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
#10 62.25       at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
#10 62.25       at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
#10 62.25       at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
#10 62.25       at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
#10 62.25       at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:74)
#10 62.25       at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:402)
#10 62.25       at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:389)
#10 62.25       at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:382)
#10 62.25       at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:368)
#10 62.25       at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
#10 62.25       at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
#10 62.25       at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
#10 62.25       at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
#10 62.25       at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
#10 62.25       at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
#10 62.25       at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61)
#10 62.25 Caused by: org.gradle.api.internal.tasks.compile.CompilationFailedException: Compilation failed; see the compiler error output for details.
#10 62.25       at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:56)
#10 62.25       at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:39)
#10 62.25       at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerWorkAction.execute(AbstractDaemonCompiler.java:135)
#10 62.25       at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
#10 62.25       at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:49)
#10 62.25       at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:43)
#10 62.25       at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)
#10 62.25       at org.gradle.workers.internal.AbstractClassLoaderWorker.executeInClassLoader(AbstractClassLoaderWorker.java:43)
#10 62.25       at org.gradle.workers.internal.FlatClassLoaderWorker.run(FlatClassLoaderWorker.java:32)
#10 62.25       at org.gradle.workers.internal.FlatClassLoaderWorker.run(FlatClassLoaderWorker.java:22)
#10 62.25       at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:85)
#10 62.25       at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:55)
#10 62.25       at org.gradle.process.internal.worker.request.WorkerAction$1.call(WorkerAction.java:138)
#10 62.25       at org.gradle.process.internal.worker.child.WorkerLogEventListener.withWorkerLoggingProtocol(WorkerLogEventListener.java:41)
#10 62.25       at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:135)
#10 62.25       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#10 62.25       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
#10 62.25       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#10 62.25       at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
#10 62.25       at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
#10 62.25       at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
#10 62.25       at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
#10 62.25       at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
#10 62.26       at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
#10 62.26       at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
#10 62.26       at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61)
#10 62.26 
```

the code around the error looks like this
```
@SuppressWarnings("NullAway.Init")
@Entity
@EntityListeners(AuditingEntityListener.class)
public class ProductRoles {

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;
  ...rest of the code
```

**Comment by tbroyer** [comment]
Apparently, openjdk:17-alpine is still a 17-ea: https://hub.docker.com/layers/openjdk/library/openjdk/17-alpine/images/sha256-a996cdcc040704ec6badaf5fecf1e144c096e00231a29188596c784bcf858d05?context=explore

And that anyMatch method's signature was changed before 17-ga: https://github.com/openjdk/jdk17u/commit/657f10393745026c3a593872b8c37403dae3adc1

**Comment by tstejl** [comment]
Thanks! I switched to `cimg/openjdk:17.0.0` and the build went through! Surprised that alpine didn't get approved for GA.
