### ISSUE TITLE
Compile error: incompatible types: cannot infer type-variable(s) T

### ISSUE THREAD

**Issue by felixdesouza** [google/error-prone#806]
Not fully sure where this should go. I'm getting a compile time error where it's not selecting the right method even though regular jdk8 javac is able to infer the right method to use.

```
Error:(16, 31) java: incompatible types: cannot infer type-variable(s) T
    (argument mismatch; bad return type in lambda expression
      missing return value)
```

Test Case:
```java
public class TestCase {

    @Test
    public void name() throws Exception {
        ExecutorService executorService = Executors.newSingleThreadExecutor();
        executorService.submit(() -> {
            System.out.println("do something and fail to compile");
            return;
        });
    }
}
```

As stated above, it works fine in plain jdk8 javac (I tried 8u112 and 8u151). It also works fine in error-prone all the up to 2.0.15.

I'm wondering whether it has anything to do with #507? If I've understood from the release notes it was introduced in 2.0.16-2.0.18 but I imagine 2.0.16? Either way, everything from 2.0.16 to 2.1.2 doesn't seem to work for me, failing with the above error.

Seems rather odd that it hasn't broken for anyone else for 9 months so I'm not sure whether it's just me.

**Comment by cushon** [comment]
This code is also rejected by the latest OpenJDK 9 javac. I think this maybe a javac bug, I reported it as [JDK-8190579](https://bugs.openjdk.java.net/browse/JDK-8190579).
