### ISSUE TITLE
NoClassDefFoundError: com/google/inject/ProvisionException

### ISSUE THREAD

**Issue by djh82** [google/error-prone#3897]
Using ErrorProne 2.19.0 with the latest dataflow Jar (3.34), ProvisionException does not appear to be on the classpath.

The stacktrace is as follows (I can't get you the full one, sorry!):

```
error-prone version: 2.19.0
BugPattern: (see stack trace)
Stack Trace:
java.lang.NoClassDefFoundError: com/google/inject/ProvisionException
    at com.google.errorprone.scanner.ScannerSupplierImpl.instantiateChecker(ScannerSupplierImpl.java:64)
```

**Comment by djh82** [comment]
Can certainly share a stacktrace when I'm back in the office tomorrow.

Everything worked fine with 2.18.0 and dataflow 3.15. Have tried 2.19.0 with dataflow 3.15 and 3.34 and the same issue occurs.

**Comment by cushon** [comment]
Thanks, can you try with `3.27.0`? That's the one we're building and testing against currently:

https://github.com/google/error-prone/blob/94a93e9ffd0aba7e0523f389a8d45cffd1b52c17/pom.xml#L38

**Comment by djh82** [comment]
> Thanks, can you try with `3.27.0`? That's the one we're building and testing against currently:
> 
> https://github.com/google/error-prone/blob/94a93e9ffd0aba7e0523f389a8d45cffd1b52c17/pom.xml#L38

As expected, this also doesnt work.

**Comment by cushon** [comment]
Sorry, I got distracted by the mention of dataflow, it makes sense that's unrelated to the missing `ProvisionException`.

The latest versions are using `ProvisionException` directly:

https://github.com/google/error-prone/blob/7335ba2402aa0b725978c3686f144e6f3de11ef1/check_api/src/main/java/com/google/errorprone/scanner/ErrorProneInjector.java#L68

There is a testonly dep on it here, which might be preventing it from being included in the `-with-deps` jar: https://github.com/google/error-prone/blob/7335ba2402aa0b725978c3686f144e6f3de11ef1/core/pom.xml#L182-L183

**Comment by lgemeinhardt** [comment]
I have the problem (usingf Java 11 or 17 used via ant) and see the same error message "Failed to find an injectable constructor for AlwaysThrows requested by AlwaysThrows" ... if I disable this check, then then next pops up "Failed to find an injectable constructor for CheckReturnValue requested by CheckReturnValue" (stacktraces below)

May this commit https://github.com/google/error-prone/commit/01e750325a476be53a5396308c650bb500faba44 makes the constructor invisible?

Stacktraces:

```
  [javac] java.lang.AssertionError: com.google.inject.ProvisionException: Unable to provision, see the following errors:
    [javac] 1) Failed to find an injectable constructor for CheckReturnValue requested by CheckReturnValue
    [javac] 1 error
    [javac] ======================
    [javac] Full classname legend:
    [javac] ======================
    [javac] CheckReturnValue: "com.google.errorprone.bugpatterns.CheckReturnValue"
    [javac] ========================
    [javac] End of classname legend:
    [javac] ========================
    [javac] 	at com.google.errorprone.ErrorProneAnalyzer.lambda$scansPlugins$0(ErrorProneAnalyzer.java:85)
    [javac] 	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183)
    [javac] 	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:152)
    [javac] 	at jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:132)
    [javac] 	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1418)
    [javac] 	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1365)
    [javac] 	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:960)
    [javac] 	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:311)
    [javac] 	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:170)
    [javac] 	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:57)
    [javac] 	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:43)
    [javac] Caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:
    [javac] 1) Failed to find an injectable constructor for CheckReturnValue requested by CheckReturnValue
    [javac] 1 error
    [javac] ======================
    [javac] Full classname legend:
    [javac] ======================
    [javac] CheckReturnValue: "com.google.errorprone.bugpatterns.CheckReturnValue"
    [javac] ========================
    [javac] End of classname legend:
    [javac] ========================
    [javac] 	at com.google.errorprone.scanner.ErrorProneInjector.lambda$getInstance$0(ErrorProneInjector.java:72)
    [javac] 	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
    [javac] 	at com.google.errorprone.scanner.ErrorProneInjector.getInstance(ErrorProneInjector.java:66)
    [javac] 	at com.google.errorprone.scanner.ErrorProneInjector.getInstance(ErrorProneInjector.java:55)
    [javac] 	at com.google.errorprone.scanner.ScannerSupplierImpl.instantiateChecker(ScannerSupplierImpl.java:66)
    [javac] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
    [javac] 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
    [javac] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
    [javac] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
    [javac] 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
    [javac] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    [javac] 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
    [javac] 	at com.google.errorprone.scanner.ScannerSupplierImpl.get(ScannerSupplierImpl.java:74)
    [javac] 	at com.google.errorprone.scanner.ScannerSupplierImpl.get(ScannerSupplierImpl.java:37)
    [javac] 	at com.google.errorprone.ErrorProneAnalyzer.lambda$scansPlugins$0(ErrorProneAnalyzer.java:80)
    [javac] 	... 10 more

```

**Comment by lgemeinhardt** [comment]
Short update regarding the "Failed to find an injectable constructor" problem - after reading https://github.com/google/error-prone/issues/3931 and the linked PR https://github.com/PicnicSupermarket/error-prone-support/pull/621/files (including adding https://search.maven.org/artifact/javax.inject/javax.inject/1/jar) I tried the same and it worked :-)
Not sure, why "javax.inject" is not part of the "with-dependencies" artifact, but adding it separately fixed it.

**Comment by cushon** [comment]
> Not sure, why "javax.inject" is not part of the "with-dependencies" artifact

I think this was an oversight, I will look at getting it included in the next release.

**Comment by cushon** [comment]
This is resolved in 2.23.0
